### ISSUE TITLE
Additional info about weather-montreal-2015-en data

### ISSUE THREAD

**Issue by folivetti** [ufabc-bcc/srbench-competition-2023-track-2-c-bio-ufpr#2]
Hello,

One additional information about the weather data. The meaning of the flags are:

"Legend"
"A","Accumulated"
"C","Precipitation occurred, amount uncertain"
"E","Estimated"
"F","Accumulated and estimated"
"L","Precipitation may or may not have occurred"
"M","Missing"
"N","Temperature missing but known to be > 0"
"S","More than one occurrence"
"T","Trace"
"Y","Temperature missing but known to be < 0"
you can get more information here https://www.kaggle.com/datasets/rosemondeld/weather-montreal-2015-en

**Comment by Martins6** [comment]
Thank you for the information! I'm sorry for the late reply! @folivetti
